services:
  database:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"
    command: master -ip=seaweedfs-master -ip.bind=0.0.0.0

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"
      - "18080:18080"
    command: volume -ip=seaweedfs-volume -ip.bind=0.0.0.0 -mserver=seaweedfs-master:9333 -port=8080
    depends_on:
      - seaweedfs-master
    volumes:
      - seaweedfs_data:/data

  seaweedfs-filer:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-filer
    ports:
      - "8888:8888"
      - "18888:18888"
    command: filer -ip=seaweedfs-filer -ip.bind=0.0.0.0 -master=seaweedfs-master:9333
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    volumes:
      - seaweedfs_filer_data:/data

  seaweedfs-s3:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-s3
    ports:
      - "8333:8333"
    command: s3 -filer=seaweedfs-filer:8888 -ip.bind=0.0.0.0
    depends_on:
      - seaweedfs-filer

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      S3_BUCKET: ${S3_BUCKET:-campus-nest}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - seaweedfs-s3


volumes:
  postgres_data:
  redis_data:
  seaweedfs_data:
  seaweedfs_filer_data:
